# Dynamic Configuration
http:
  routers:
    random-router:
      rule: "Host(`traefikapi.iata-poc.nborbit.ca`)"
      service: "traefikapi"
      entryPoints:
        - "websecure"
      tls:
        certResolver: "acmeresolver"
      middlewares:
        - "cors-allow-all@file"

  services:
    traefikapi:
      loadBalancer:
        servers:
          - url: "http://traefik-traefik-manager-1:8000"

  middlewares:
    cors-allow-all:
      headers:
        accessControlAllowCredentials: true
        accessControlAllowHeaders:
          - "*"
        accessControlAllowMethods:
          - "GET"
          - "OPTIONS"
          - "PUT"
          - "POST"
          - "DELETE"
        accessControlAllowOriginList:
          - "*"
        accessControlExposeHeaders:
          - "*"
        accessControlMaxAge: 100

tls:
  options:
    default:
      minVersion: "VersionTLS12"
