version: '3.7'

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.acmeresolver.acme.dnschallenge.provider=route53"
      - "--certificatesresolvers.acmeresolver.acme.email=${AWS_CERT_EMAIL}"
      - "--certificatesresolvers.acmeresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      - docker_orbitNetwork

  traefik-config-manager:
    image: your-service-image
    container_name: traefik-traefik-config-manager-1
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - ENABLE_S3_BACKUP=${ENABLE_S3_BACKUP}
      - CONFIG_FILE=/etc/traefik/dynamic/config.yaml
      - LOCAL_BACKUP_DIR=/etc/traefik/backups
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - CERT_RESOLVER=route53
      - AWS_HOSTED_ZONE_ID=${AWS_HOSTED_ZONE_ID}
      - AWS_CERT_EMAIL=${AWS_CERT_EMAIL}
    networks:
      - docker_orbitNetwork

networks:
  docker_orbitNetwork:
    driver: bridge