version: '3.7'

services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.acmeresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.acmeresolver.acme.dnschallenge.provider=route53"
      - "--certificatesresolvers.acmeresolver.acme.email=${AWS_CERT_EMAIL}"
      - "--certificatesresolvers.acmeresolver.acme.storage=/etc/traefik/acme/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    networks:
      - docker_orbitNetwork
    labels:
      - "traefik.enable=true"

  traefik-manager:
    build: .
    container_name: traefik-manager
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - ENABLE_S3_BACKUP=${ENABLE_S3_BACKUP}
      - CONFIG_FILE=/etc/traefik/dynamic/config.yaml
      - LOCAL_BACKUP_DIR=/etc/traefik/backups
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - CERT_RESOLVER=route53
      - AWS_HOSTED_ZONE_ID=${AWS_HOSTED_ZONE_ID}
      - AWS_CERT_EMAIL=${AWS_CERT_EMAIL}
    volumes:
      - traefik-config:/etc/traefik
    networks:
      - docker_orbitNetwork

networks:
  docker_orbitNetwork:
    driver: bridge

volumes:
  traefik-config:
    name: traefik-config