version: '3.7'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.acmeresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.acmeresolver.acme.dnschallenge.provider=route53"
      - "--certificatesresolvers.acmeresolver.acme.email=${AWS_CERT_EMAIL}"
      - "--certificatesresolvers.acmeresolver.acme.storage=/etc/traefik/acme/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - config-volume:/etc/traefik/dynamic:rw
      - acme-volume:/etc/traefik/acme:rw
    networks:
      - docker_orbitNetwork
    labels:
      - "traefik.enable=true"
    depends_on:
      init-config:
        condition: service_completed_successfully

  # Add init service to set up ACME permissions
  init-acme:
    image: alpine
    command: >
      sh -c "mkdir -p /etc/traefik/acme && 
             touch /etc/traefik/acme/acme.json && 
             chmod 600 /etc/traefik/acme/acme.json"
    volumes:
      - acme-volume:/etc/traefik/acme:rw

  traefik-manager:
    build: .
    container_name: traefik-manager
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - ENABLE_S3_BACKUP=${ENABLE_S3_BACKUP}
      - CONFIG_FILE=/etc/traefik/dynamic/config.yaml
      - LOCAL_BACKUP_DIR=/etc/traefik/backups
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - CERT_RESOLVER=route53
      - AWS_HOSTED_ZONE_ID=${AWS_HOSTED_ZONE_ID}
      - AWS_CERT_EMAIL=${AWS_CERT_EMAIL}
    volumes:
      - config-volume:/etc/traefik/dynamic:rw
    networks:
      - docker_orbitNetwork
    depends_on:
      - init-acme

  # Add initialization service
  init-config:
    image: alpine
    volumes:
      - config-volume:/etc/traefik/dynamic
      - ./config.yaml:/tmp/config.yaml:ro
    command: >
      sh -c "mkdir -p /etc/traefik/dynamic && 
             cp /tmp/config.yaml /etc/traefik/dynamic/config.yaml && 
             chmod 644 /etc/traefik/dynamic/config.yaml"

volumes:
  config-volume:
    name: traefik-config-volume
  acme-volume:
    name: traefik-acme-volume

networks:
  docker_orbitNetwork:
    external: true